name: Ci main

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version:
        type: string
        description: Release version
        required: true

jobs:
  build:
    if: github.actor == 'doquockhanhan'
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variable
      run: |
        echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/verify-contract:${{ inputs.version }} >> $GITHUB_ENV
        echo REPO_MANIFEST_NAME=gitops-prod >> $GITHUB_ENV
        echo REPO_MANIFEST_URL=github.com/aura-nw/gitops-prod.git >> $GITHUB_ENV
        echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
        echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-xstaxy/explorer >> $GITHUB_ENV
        echo REPO_MANIFEST_TAG_IMAGE=image_verify_contract >> $GITHUB_ENV
    - name: Build the Docker image and push it to the registry
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls -al /bin
        chmod 777 -R ./ci
        ./ci/build.sh
    - name: Update manifest
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        ./ci/updateManifest.sh